import "./globals.css";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";
import BottomBar from "./components/BottomBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project Catalyzers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          {children}
          <BottomBar />
        </AuthContextProvider>
      </body>
    </html>
  );
}
